---
- name: Remove Oracle dump dir
  file:
    state: absent
    path: "{{ backup_restore_item|c2platform.mgmt.role_dump_dir(vars) }}"

- name: Create Oracle dump dir
  file:
    state: directory
    path: "{{ backup_restore_item|c2platform.mgmt.role_dump_dir(vars) }}"
    mode: 0777
    recurse: yes

- name: Extract Oracle dump dir tar
  unarchive:
    src: "{{ backup_restore[backup_restore_item]['db_tar'] }}"
    remote_src: yes
    dest: "{{ backup_restore_item|c2platform.mgmt.role_dump_dir(vars) }}"
  when: backup_restore[backup_restore_item]['db_tar'] is defined

- name: Drop existing schema ( if it exists )
  command: "{{ backup_restore_item|c2platform.mgmt.role_script_path('drop_schema.sh') }}"
  when:
    backup_restore[backup_restore_item]['db_tar'] is defined or
    backup_roles[backup_restore_item]['incremental']
  environment:
    TPELCM_CONFIRM: 'Y'

- name: Run database import
  command: "{{ backup_restore_item|c2platform.mgmt.role_script_path('impdp.sh') }}"
  when:
    backup_restore[backup_restore_item]['db_tar'] is defined or
    backup_roles[backup_restore_item]['incremental']
  environment:
    TPELCM_CONFIRM: 'Y'
