---
- name: Extract home tar
  unarchive:
    src: "{{ backup_restore[backup_restore_item]['home_tar'] }}"
    remote_src: yes
    dest: "{{ backup_restore[backup_restore_item]['tmp'] }}/home"
    extra_opts: "{{ backup_home_tar_unarchive_extra_opts|default(omit) }}"
  when: backup_restore[backup_restore_item]['home_tar'] is defined

- name: Restore files
  command: "rsync -az --delete --recursive {{ backup_restore[backup_restore_item]['rsync-src'] }} {{ backup_restore[backup_restore_item]['rsync-target'] }}"
  when: backup_restore[backup_restore_item]['home_tar'] is defined or backup_roles[backup_restore_item]['incremental']

- name: Delete folders
  file:
    state: absent
    path: "{{ backup_restore[backup_restore_item]['remove_folder_expanded'] }}"
  when: backup_restore[backup_restore_item]['remove_folder_expanded'] is defined
