---
- include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: Debug upgrade results
  debug:
    var: server_update_results
  when: server_update_debug|bool

# Reboot module does not work / hangs / waits indefinitely
#- name: Restart server
#  reboot:
#    pre_reboot_delay: "{{ server_update_reboot_pre_delay }}"
#    post_reboot_delay: "{{ server_update_reboot_post_delay }}"
#    reboot_timeout: "{{ server_update_reboot_timeout }}"
#    reboot_command: "{{ server_update_reboot_command|default(omit) }}"
#  when: server_update_reboot_enabled|bool and server_update_reboot|bool

- block:
  - name: Restart server
    shell: /sbin/shutdown -r now "Ansible system package upgraded"
    async: 1
    poll: 0

  - set_fact:
      wait_host: "{{ ansible_host }}"

  - name: Wait for server
    local_action: wait_for host={{wait_host}} delay=20 port=22 state=started
    become: false
  when: server_update_reboot_enabled|bool and server_update_reboot|bool
