---
- name: Apt key
  apt_key:
    url: https://repo.bkwi.local/ubuntu/mirror/packages.icinga.com/icinga.key

- name: Apt repository icinga-bionic
  apt_repository:
    codename: icinga-bionic
    repo: deb http://repo.bkwi.local/ubuntu/mirror/packages.icinga.com/ubuntu icinga-bionic main
    filename: icinga2-release

- name: Install package
  apt:
    name: icinga2
    state: present
    update_cache: yes

- name: Creates configuration directory
  file:
    path: /etc/icinga2/objects.d
    state: directory
    owner: nagios
    group: nagios
    mode: 0750

- name: Setup icinga2 configuration
  template:
    src: icinga2.conf.j2
    dest: /etc/icinga2/icinga2.conf
    backup: yes
    mode: 0640
    owner: nagios
    group: nagios

- name: Setup endpoint configuration
  template:
    src: endpoint.conf.j2
    dest: /etc/icinga2/objects.d/endpoint.conf
    backup: yes
    mode: 0640
    owner: nagios
    group: nagios

- name: Setup zone configuration
  template:
    src: zone.conf.j2
    dest: /etc/icinga2/objects.d/zone.conf
    backup: yes
    mode: 0640
    owner: nagios
    group: nagios

- name: Setup api listener configuration
  template:
    src: apilistener.conf.j2
    dest: /etc/icinga2/objects.d/apilistener.conf
    backup: yes
    mode: 0640
    owner: nagios
    group: nagios

- name: Create certificates directory
  file:
    path: /var/lib/icinga2/certs
    state: directory
    owner: nagios
    group: nagios

- name: Create client certificate
  shell: |
    icinga2 pki new-cert --cn {{ ansible_fqdn }} \
                         --key /var/lib/icinga2/certs/{{ ansible_fqdn }}.key \
                         --cert /var/lib/icinga2/certs/{{ ansible_fqdn }}.crt 

- name: Set the master certificate
  shell: |
    icinga2 pki save-cert --key /var/lib/icinga2/certs/{{ ansible_fqdn }}.key \
                          --cert /var/lib/icinga2/certs/{{ ansible_fqdn }}.crt \
                          --trustedcert /var/lib/icinga2/certs/trusted-master.crt \
                          --host {{ icinga2_master }} \
                          --port {{ icinga2_port }}

- name: Request master CA
  shell: |
    icinga2 pki request \
                --host {{ icinga2_master }} \
                --port {{ icinga2_port }} \
                --key /var/lib/icinga2/certs/{{ ansible_fqdn }}.key \
                --cert /var/lib/icinga2/certs/{{ ansible_fqdn }}.crt \
                --trustedcert /var/lib/icinga2/certs/trusted-master.crt \
                --ca /var/lib/icinga2/certs/ca.crt

- name: Enable and restart Icinga2
  service:
    name: icinga2
    state: restarted
    enabled: yes
