---
- name: Apt key
  apt_key:
    url: https://packages.icinga.com/icinga.key

- name: Apt repository icinga-bionic
  apt_repository:
    codename: icinga-bionic
    repo: deb http://packages.icinga.com/ubuntu icinga-bionic main
    filename: icinga2-release

- name: Install package
  apt:
    name: icinga2
    state: present

- name: Creates configuration directory
  file:
    path: /etc/icinga2/objects.d
    state: directory
    owner: nagios
    group: nagios
    mode: 0750

#- name: Copy default configuration files
#  template:
#    src: apilistener.conf.j2
#    dest: /etc/icinga2/objects.d/apilistener.conf
#    owner: nagios
#    group: nagios
#    mode: 0750